### ISSUE TITLE
Beta testing

### ISSUE THREAD

**Issue by paulinaaniola** [bardss/TSD-PokerPlanning#77]
Beta test application to check if everything works fine.

AC1: Player have possibility to work with other users
AC2: Users have possibility to do estimation multiple times

**Comment by bardss** [comment]
There was problems with error understanding on Login and Register screens.
Will be solved in issue: https://github.com/KristiSik/TSD-PokerPlanning/issues/46

**Comment by paulinaaniola** [comment]
There was a problem with horizontal mode and it was solved in issue: #80

**Comment by bardss** [comment]
There was problem with ready status on game repeat on same room. https://github.com/KristiSik/TSD-PokerPlanning/issues/81

**Comment by bardss** [comment]
All of problems are having solutions. All done and fixed.
Application released.
